---
title: "World Heritage Mobilization Status"
date: "`r Sys.Date()`"
author: Chandra Earl
output: (function(...) {
  rmdformats::robobook(toc_depth = 1, pandoc_args = c("+RTS", "-K2000m", "-RTS"), ...) })
editor_options: 
  chunk_output_type: console
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = ".") })  
---




| Site                                                                                      | Citation                                      | Data Type      | Raw Data Link                                                                                                                                                                                                                                                                | Notebook Link                                                                                                                                                  | GBIF Dataset Link                       |
| ----------------------------------------------------------------------------------------- | --------------------------------------------- | -------------- | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------------------------------------------------------------------------- | --------------------------------------- |
| Aldabra Atoll                                                                             | Downing and Stobart 2021                      | Occurrence     | [Link](https://www.aldabra.org/wp-content/uploads/2022/02/Report-on-December-2021-Aldabra-surveys-230222-1.pdf)                                                                                                                                                              | [Link](https://iobis.github.io/mwhs-data-mobilization/notebooks/aldabra_atoll/Downing_and_Stobart_2021)                                                        | [Link](https://doi.org/10.25607/fsbkww) |
| Aldabra Atoll                                                                             | Friedlander et al. 2015                       | Checklist      | [Link](http://dx.doi.org/10.13140/RG.2.2.14095.69282)                                                                                                                                                                                                                        | [Link](https://iobis.github.io/mwhs-data-mobilization/notebooks/aldabra_atoll/Friedlander_et_al_2015)                                                          | [Link](https://doi.org/10.25607/l1md8g) |
| Aldabra Atoll                                                                             | Aldabra Research Station 2023                 | Checklist      | [Link](https://figshare.com/articles/dataset/Reef_fish_abundance_size_and_biomass_from_Aldabra_Atoll_Seychelles_between_2014_and_2021_collected_by_the_Seychelles_Islands_Foundation_/22792580)                                                                              | [Link](https://iobis.github.io/mwhs-data-mobilization/notebooks/aldabra_atoll/Aldabra_Research_Station_2023)                                                   | [Link](https://doi.org/10.25607/hpsg9j) |
| Archipiélago de Revillagigedo                                                             | Del Moral-Flores et al. 2016                  | Checklist      | [Link](https://doi.org/10.22201/fesi.20072082.2016.9.75910)                                                                                                                                                                                                                  | [Link](https://iobis.github.io/mwhs-data-mobilization/notebooks/archipielago_de_revillagigedo/Del_Moral-Flores_et_al_2016)                                     | [Link](https://doi.org/10.25607/as6pox) |
| Archipiélago de Revillagigedo                                                             | Fourriere et al. 2016                         | Checklist      | [Link](https://doi.org/10.11646/zootaxa.4150.4.4)                                                                                                                                                                                                                            | [Link](https://iobis.github.io/mwhs-data-mobilization/notebooks/archipielago_de_revillagigedo/Forriere_et_al_2016)                                             | [Link](https://doi.org/10.25607/zevqp7) |
| Archipiélago de Revillagigedo                                                             | Hollarsmith et al. 2020                       | Occurrence     | [Link](http://dx.doi.org/10.1111/jbi.13842)                                                                                                                                                                                                                                  | [Link](https://iobis.github.io/mwhs-data-mobilization/notebooks/archipielago_de_revillagigedo/Hollarsmith_et_al_2020)                                          | [Link](https://doi.org/10.25607/edzdnx) |
| Archipiélago de Revillagigedo                                                             | Robertson and Allen 2015                      | Checklist      | [Link](https://biogeodb.stri.si.edu/sftep/en/pages)                                                                                                                                                                                                                          | [Link](https://iobis.github.io/mwhs-data-mobilization/notebooks/archipielago_de_revillagigedo/Robertson_and_Allen_2015)                                        | [Link](https://doi.org/10.25607/wbcgjt) |
| Banc d'Arguin National Park                                                               | Gushin and Fall 2012                          | Checklist      | [Link](https://doi.org/10.1134/S0032945212010055)                                                                                                                                                                                                                            | [Link](https://iobis.github.io/mwhs-data-mobilization/notebooks/banc_darguin_national_park/Gushin_and_Fall_2012/)                                              | [Link](https://doi.org/10.25607/ihbtkl) |
| Banc d'Arguin National Park                                                               | Jager 1993                                    | Checklist      | [Link](https://doi.org/10.1007/BF00006196)                                                                                                                                                                                                                                   | [Link](https://iobis.github.io/mwhs-data-mobilization/notebooks/banc_darguin_national_park/Jager_et_al_1993/)                                                  | [Link](https://doi.org/10.25607/mwvy2h) |
| Banc d'Arguin National Park                                                               | Tregarot et al. 2018                          | Checklist      | [Link](https://horizon.documentation.ird.fr/exl-doc/pleins_textes/divers19-04/010075369.pdf)                                                                                                                                                                                 | [Link](https://iobis.github.io/mwhs-data-mobilization/notebooks/banc_darguin_national_park/Tregarot_et_al_2018/)                                               | [Link](https://doi.org/10.25607/4dwy89) |
| Banc d'Arguin National Park                                                               | Compain 2021                                  | Occurrence     | [Link](https://sapientia.ualg.pt/bitstream/10400.1/17835/1/Thesis%20%28digital%20version%29%20Nicolas%20COMPAIN%20a68831.pdf)                                                                                                                                                | [Link](https://iobis.github.io/mwhs-data-mobilization/notebooks/banc_darguin_national_park/Compain_2021)                                                       | [Link](https://doi.org/10.25607/n1euud) |
| Banc d'Arguin National Park                                                               | de la Hoz Schilling 2021                      | eDNA           | [Link](https://sapientia.ualg.pt/bitstream/10400.1/18173/1/de_la_Hoz_Schilling_Carolina_67318_Master_thesis_2021.pdf)                                                                                                                                                        | [Link](https://iobis.github.io/mwhs-data-mobilization/notebooks/banc_darguin_national_park/de_la_Hoz_Schilling_2021)                                           | [Link](https://doi.org/10.25607/bce6up) |
| Banc d'Arguin National Park                                                               | van Etten 2002                                | Occurrence     | [Link](https://fse.studenttheses.ub.rug.nl/id/eprint/9188)                                                                                                                                                                                                                   | [Link](https://iobis.github.io/mwhs-data-mobilization/notebooks/banc_darguin_national_park/van_Etten_2002)                                                     | [Link](https://doi.org/10.25607/7hpana) |
| Banc d'Arguin National Park                                                               | CCMAR 2023                                    | Occurrence     | [Link](https://www.marafrica.net/pnba/records/)                                                                                                                                                                                                                              | [Link](https://iobis.github.io/mwhs-data-mobilization/notebooks/banc_darguin_national_park/CCMAR_2023)                                                         | [Link](https://doi.org/10.25607/krhjji) |
| Belize Barrier Reef Reserve System                                                        | Alicea 2010                                   | Checklist      | [Link](https://repository.library.noaa.gov/view/noaa/820)                                                                                                                                                                                                                    | [Link](https://iobis.github.io/mwhs-data-mobilization/notebooks/belize_barrier_reef_reserve_system/Alicea_2010)                                                | [Link](https://doi.org/10.25607/59lxtd) |
| Belize Barrier Reef Reserve System                                                        | Villela 2003                                  | Checklist      | [Link](https://rris.biopama.org/sites/default/files/2021-03/MBRS%20synoptic%20monitoring.pdf)                                                                                                                                                                                | [Link](https://iobis.github.io/mwhs-data-mobilization/notebooks/belize_barrier_reef_reserve_system/Villela_et_al_2003)                                         | [Link](https://doi.org/10.25607/giyrkr) |
| ~~Belize Barrier Reef Reserve System~~                                                    | ~~Robertson and Allen 2015~~                  | ~~Checklist~~  | [~~Link~~](https://biogeodb.stri.si.edu/caribbean/en/)                                                                                                                                                                                                                       | \---                                                                                                                                                           | \---                                    |
| Brazilian Atlantic Islands: Fernando de Noronha and Atol das Rocas Reserves               | Batista et al. 2012                           | Occurrence     | [Link](http://dx.doi.org/10.15560/8.3.584)                                                                                                                                                                                                                                   | [Link](https://iobis.github.io/mwhs-data-mobilization/notebooks/brazilian_atlantic_islands_fernando_de_noronha_and_atol_das_rocas_reserves/Batista_et_al_2012) | [Link](https://doi.org/10.25607/vvgeub) |
| Brazilian Atlantic Islands: Fernando de Noronha and Atol das Rocas Reserves               | Eduardo et al. 2022                           | Occurrence     | [Link](https://doi.org/10.3389/fmars.2022.937154)                                                                                                                                                                                                                            | [Link](https://iobis.github.io/mwhs-data-mobilization/notebooks/brazilian_atlantic_islands_fernando_de_noronha_and_atol_das_rocas_reserves/Eduardo_et_al_2022) | [Link](https://doi.org/10.25607/kr0wqx) |
| ~~Brazilian Atlantic Islands: Fernando de Noronha and Atol das Rocas Reserves~~           | ~~Krajewski and Floeter 2011~~                | ~~Occurrence~~ | [~~Link~~](https://doi.org/10.1007/s10641-011-9813-3)                                                                                                                                                                                                                        | \---                                                                                                                                                           | \---                                    |
| ~~Brazilian Atlantic Islands: Fernando de Noronha and Atol das Rocas Reserves~~           | ~~Mincarone et al. 2022~~                     | ~~Occurrence~~ | [~~Link~~](https://doi.org/10.1111/jfb.15155)                                                                                                                                                                                                                                | \---                                                                                                                                                           | \---                                    |
| Brazilian Atlantic Islands: Fernando de Noronha and Atol das Rocas Reserves               | Sazima et al. 2006                            | Checklist      | [Link](https://doi.org/10.1590/S1679-62252006000400009)                                                                                                                                                                                                                      | [Link](https://iobis.github.io/mwhs-data-mobilization/notebooks/brazilian_atlantic_islands_fernando_de_noronha_and_atol_das_rocas_reserves/Sazima_et_al_2006)  | [Link](https://doi.org/10.25607/wyztua) |
| Brazilian Atlantic Islands: Fernando de Noronha and Atol das Rocas Reserves               | Schmid et al. 2020                            | Checklist      | [Link](https://doi.org/10.1590/1676-0611-BN-2020-1014)                                                                                                                                                                                                                       | [Link](https://iobis.github.io/mwhs-data-mobilization/notebooks/brazilian_atlantic_islands_fernando_de_noronha_and_atol_das_rocas_reserves/Schmid_et_al_2020)  | [Link](https://doi.org/10.25607/wcxq31) |
| Brazilian Atlantic Islands: Fernando de Noronha and Atol das Rocas Reserves               | Soto 2001                                     | Checklist      | [Link](https://www.univali.br/institucional/museu-oceanografico-univali/mare-magnum/volume-1-numero-2/Documents/maremagnum14.pdf)                                                                                                                                            | [Link](https://iobis.github.io/mwhs-data-mobilization/notebooks/brazilian_atlantic_islands_fernando_de_noronha_and_atol_das_rocas_reserves/Soto_2001)          | [Link](https://doi.org/10.25607/bwuflp) |
| Brazilian Atlantic Islands: Fernando de Noronha and Atol das Rocas Reserves               | CIUFES 2023                                   | Occurrence     | [Link](https://specieslink.net/col/CIUFES/)                                                                                                                                                                                                                                  | [Link](https://iobis.github.io/mwhs-data-mobilization/notebooks/brazilian_atlantic_islands_fernando_de_noronha_and_atol_das_rocas_reserves/CIUFES_2023)        | [Link](https://doi.org/10.25607/s1dwgs) |
| Cocos Island National Park                                                                | Fourriere et al. 2017                         | Checklist      | [Link](http://dx.doi.org/10.1007/s12526-016-0501-6)                                                                                                                                                                                                                          | [Link](https://iobis.github.io/mwhs-data-mobilization/notebooks/cocos_island_national_park/Fourriere_et_al_2017)                                               | [Link](https://doi.org/10.25607/ty53k6) |
| Cocos Island National Park                                                                | Robertson and Allen 2015                      | Checklist      | [Link](https://biogeodb.stri.si.edu/sftep/en/pages)                                                                                                                                                                                                                          | [Link](https://iobis.github.io/mwhs-data-mobilization/notebooks/cocos_island_national_park/Robertson_and_Allen_2015)                                           | [Link](https://doi.org/10.25607/bjlwjp) |
| Coiba National Park and its Special Zone of Marine Protection                             | Glynn and Fong 2014                           | Occurrence     | [Link](https://doi.org/10.1575/1912/bco-dmo.516234.1)                                                                                                                                                                                                                        | [Link](https://iobis.github.io/mwhs-data-mobilization/notebooks/coiba_national_park_and_its_special_zone_of_marine_protection/Glynn_and_Fong_2014)             | [Link](https://doi.org/10.25607/orijco) |
| Coiba National Park and its Special Zone of Marine Protection                             | Nunez et al. 2010                             | Occurrence     | [Link](https://revistas.up.ac.pa/index.php/tecnociencia/article/view/874/743)                                                                                                                                                                                                | [Link](https://iobis.github.io/mwhs-data-mobilization/notebooks/coiba_national_park_and_its_special_zone_of_marine_protection/Nunez_et_al_2010)                | [Link](https://doi.org/10.25607/yxpxox) |
| Coiba National Park and its Special Zone of Marine Protection                             | Robertson and Allen 2015                      | Checklist      | [Link](https://biogeodb.stri.si.edu/sftep/en/pages)                                                                                                                                                                                                                          | [Link](https://iobis.github.io/mwhs-data-mobilization/notebooks/coiba_national_park_and_its_special_zone_of_marine_protection/Robertson_and_Allen_2015)        | [Link](https://doi.org/10.25607/dbtlzu) |
| Coiba National Park and its Special Zone of Marine Protection                             | Robertson et al 2003                          | Occurrence     | [Link](http://dx.doi.org/10.13140/RG.2.1.3983.6008)                                                                                                                                                                                                                          | [Link](https://iobis.github.io/mwhs-data-mobilization/notebooks/coiba_national_park_and_its_special_zone_of_marine_protection/Robertson_et_al_2003)            | [Link](https://doi.org/10.25607/sj4lfy) |
| Coiba National Park and its Special Zone of Marine Protection                             | Vega and Villarreal 2003                      | Occurrence     | [Link](http://up-rid.up.ac.pa/874/1/Tecnociencia%20Articulo%205%205%281%29%2003.pdf)                                                                                                                                                                                         | [Link](https://iobis.github.io/mwhs-data-mobilization/notebooks/coiba_national_park_and_its_special_zone_of_marine_protection/Vega_and_Villarreal_2003)        | [Link](https://doi.org/10.25607/lut8bf) |
| ~~Everglades National Park~~                                                              | ~~Kline et al. 2014~~                         | ~~Checklist~~  | [~~Link~~](https://doi.org/10.1007/s13157-012-0362-0)                                                                                                                                                                                                                        | \---                                                                                                                                                           | \---                                    |
| Everglades National Park                                                                  | Loftus 2000                                   | Checklist      | [Link](https://www.jstor.org/stable/24321054)                                                                                                                                                                                                                                | Link                                                                                                                                                           | [Link](https://doi.org/10.25607/dpvccz) |
| ~~Everglades National Park~~                                                              | ~~Robertson and Allen 2015~~                  | ~~Checklist~~  | [~~Link~~](https://biogeodb.stri.si.edu/caribbean/en/)                                                                                                                                                                                                                       | \---                                                                                                                                                           | \---                                    |
| French Austral Lands and Seas                                                             | Hill et al. 2017                              | Checklist      | [Link](https://doi.org/10.1111/ddi.12613)                                                                                                                                                                                                                                    | [Link](https://iobis.github.io/mwhs-data-mobilization/notebooks/french_austral_lands_and_seas/Hill_et_al_2017)                                                 | [Link](https://doi.org/10.25607/y6v0zw) |
| Gulf of Porto: Calanche of Piana, Gulf of Girolata, Scandola Reserve                      | Miniconi et al. 1990                          | Checklist      | [Link](https://sfi-cybium.fr/fr/inventaire-de-la-faune-ichtyologique-de-la-r%C3%A9serve-naturelle-de-scandola-corse-m%C3%A9diterran%C3%A9e-nord)                                                                                                                             | [Link](https://iobis.github.io/mwhs-data-mobilization/notebooks/gulf_of_porto_calanche_of_piana_gulf_of_girolata_scandola_reserve/Miniconi_et_al_1990/)        | [Link](https://doi.org/10.25607/k7ga1p) |
| Gulf of Porto: Calanche of Piana, Gulf of Girolata, Scandola Reserve                      | Dufour et al. 2007                            | Checklist      | [Link](https://sfi-cybium.fr/sites/default/files/pdfs-cybium/05.Dufour%20424.pdf)                                                                                                                                                                                            | [Link](https://iobis.github.io/mwhs-data-mobilization/notebooks/gulf_of_porto_calanche_of_piana_gulf_of_girolata_scandola_reserve/Dufour_et_al_2007)           | [Link](https://doi.org/10.25607/zyvtaz) |
| Gulf of Porto: Calanche of Piana, Gulf of Girolata, Scandola Reserve                      | INPN 2023                                     | Checklist      | [Link](https://inpn.mnhn.fr/espace/protege/FR7100002/tab/especes?lg=en)                                                                                                                                                                                                      | [Link](https://iobis.github.io/mwhs-data-mobilization/notebooks/gulf_of_porto_calanche_of_piana_gulf_of_girolata_scandola_reserve/INPN_2023)                   | [Link](https://doi.org/10.25607/ydaydn) |
| ~~Gulf of Porto: Calanche of Piana, Gulf of Girolata, Scandola Reserve~~                  | ~~Francour et al. 2010~~                      | ~~Checklist~~  | ~~Link~~                                                                                                                                                                                                                                                                     | \---                                                                                                                                                           | \---                                    |
| Lagoons of New Caledonia: Reef Diversity and Associated Ecosystems                        | Fricke et al. 2011                            | Checklist      | [Link](https://www.zobodat.at/pdf/Stuttgarter-Beitraege-Naturkunde_NS_4_A_0341-0363.pdf)                                                                                                                                                                                     | [Link](https://iobis.github.io/mwhs-data-mobilization/notebooks/lagoons_of_new_caledonia_reef_diversity_and_associated_ecosystems/Fricke_et_al_2011)           | [Link](https://doi.org/10.25607/fq9y4b) |
| ~~Lagoons of New Caledonia: Reef Diversity and Associated Ecosystems~~                    | ~Mathon et al. 2022~~                         | ~~eDNA~~       | [~~Link~~](https://doi.org/10.1098/rspb.2022.0162)                                                                                                                                                                                                                           | \---                                                                                                                                                           | \---                                    |
| ~~Lagoons of New Caledonia: Reef Diversity and Associated Ecosystems~~                    | ~~Boussarie et al. 2018~~                     | ~~eDNA~~       | [~~Link~~](https://doi.org/10.1126/sciadv.aap9661)                                                                                                                                                                                                                           | \---                                                                                                                                                           | \---                                    |
| Lagoons of New Caledonia: Reef Diversity and Associated Ecosystems                        | Bakker et al. 2017                            | eDNA           | [Link](https://doi.org/10.1038/s41598-017-17150-2)                                                                                                                                                                                                                           | [Link](https://iobis.github.io/mwhs-data-mobilization/notebooks/lagoons_of_new_caledonia_reef_diversity_and_associated_ecosystems/Bakker_et_al_2017)           | [Link](https://doi.org/10.25607/tciqld) |
| Lord Howe Island Group                                                                    | Davis et al. 2018                             | Checklist      | [Link](https://doi.org/10.1016/j.rsma.2018.09.002)                                                                                                                                                                                                                           | [Link](https://iobis.github.io/mwhs-data-mobilization/notebooks/lord_howe_island_group/Davis_et_al_2018)                                                       | [Link](https://doi.org/10.25607/eaddvw) |
| Lord Howe Island Group                                                                    | Francis 1993                                  | Checklist      | [Link](http://dx.doi.org/10.6084/m9.figshare.c.4428305)                                                                                                                                                                                                                      | [Link](https://iobis.github.io/mwhs-data-mobilization/notebooks/lord_howe_island_group/Francis_1993)                                                           | [Link](https://doi.org/10.25607/wtx3w5) |
| ~~Lord Howe Island Group~~                                                                | ~~Francis and Randall 1993~~                  | ~Checklist~~   | [~~Link~~](https://scholarspace.manoa.hawaii.edu/server/api/core/bitstreams/424ceef3-55c4-431b-bd66-ce01dc08b33a/content)                                                                                                                                                    | \---                                                                                                                                                           | \---                                    |
| ~~Lord Howe Island Group~~                                                                | ~~Zintzen et al. 2009~~                       | ~~Occurrence~~ | [~~Link~~](http://dx.doi.org/10.1016/j.dsr2.2010.10.049)                                                                                                                                                                                                                     | \---                                                                                                                                                           | \---                                    |
| Península Valdés                                                                          | Galvan et al. 2009                            | Checklist      | [Link](http://dx.doi.org/10.2174/1874401X00902010090)                                                                                                                                                                                                                        | [Link](https://iobis.github.io/mwhs-data-mobilization/notebooks/peninsula_valdes/Galvan_et_al_2009)                                                            | [Link](https://doi.org/10.25607/pdf4hx) |
| Península Valdés                                                                          | Maestro et al. 1998                           | Checklist      | [Link](https://peninsulavaldes.org.ar/descargas/)                                                                                                                                                                                                                            | [Link](https://iobis.github.io/mwhs-data-mobilization/notebooks/peninsula_valdes/Maestro_et_al_1998)                                                           | [Link](https://doi.org/10.25607/e1ikzp) |
| ~~Sanganeb Marine National Park and Dungonab Bay - Mukkawar Island Marine National Park~~ | ~~African Parks Foundation 2006~~             | ~~Checklist~~  | ~~Link~~                                                                                                                                                                                                                                                                     | \---                                                                                                                                                           | \---                                    |
| ~~Sanganeb Marine National Park and Dungonab Bay - Mukkawar Island Marine National Park~~ | ~~Kept et al. 2002~~                          | ~~Checklist~~  | ~~Link~~                                                                                                                                                                                                                                                                     | \---                                                                                                                                                           | \---                                    |
| ~~Sanganeb Marine National Park and Dungonab Bay - Mukkawar Island Marine National Park~~ | ~~PERSGA/GEF 2004~~                           | ~~Checklist~~  | ~~Link~~                                                                                                                                                                                                                                                                     | \---                                                                                                                                                           | \---                                    |
| ~~Shark Bay, Western Australia~~                                                          | ~~Clough 2011~~                               | ~~Checklist~~  | [~~Link~~](https://static1.squarespace.com/static/5f1710136a45566857f743d5/t/616522b70276a61009b4656b/1634017978053/Clough_Thesis+20_11_2012.pdf)                                                                                                                            | \---                                                                                                                                                           | \---                                    |
| Shark Bay, Western Australia                                                              | Heithaus 2004                                 | Checklist      | [Link](http://www.monkeymiadolphins.org/wp-content/uploads/2019/10/Heithaus-2004.pdf)                                                                                                                                                                                        | [Link](https://iobis.github.io/mwhs-data-mobilization/notebooks/shark_bay_western_australia/Heithaus_2004)                                                     | [Link](https://doi.org/10.25607/yppfqu) |
| Shark Bay, Western Australia                                                              | Hutchins 1990                                 | Checklist      | Link                                                                                                                                                                                                                                                                         | [Link](https://iobis.github.io/mwhs-data-mobilization/notebooks/shark_bay_western_australia/Hutchins_1990)                                                     | [Link](https://doi.org/10.25607/zzrggg) |
| ~~Shark Bay, Western Australia~~                                                          | ~~Kangas and Morrison 2013~~                  | ~~Occurrence~~ | [~~Link~~](https://doi.org/10.1071/MF12292)                                                                                                                                                                                                                                  | \---                                                                                                                                                           | \---                                    |
| Shark Bay, Western Australia                                                              | Kangas et al. 2007                            | Checklist      | [Link](https://www.fish.wa.gov.au/Documents/research_reports/frr160.pdf)                                                                                                                                                                                                     | [Link](https://iobis.github.io/mwhs-data-mobilization/notebooks/shark_bay_western_australia/Kangas_et_al_2007)                                                 | [Link](https://doi.org/10.25607/rklus6) |
| ~~Shark Bay, Western Australia~~                                                          | ~~Wise et al. 2012~~                          | ~~Occurrence~~ | [~~Link~~](https://doi.org/10.1071/MF12054)                                                                                                                                                                                                                                  | \---                                                                                                                                                           | \---                                    |
| Socotra Archipelago                                                                       | Zajonz et al. 2022                            | Checklist      | [Link](https://doi.org/10.1371/journal.pone.0267086)                                                                                                                                                                                                                         | [Link](https://iobis.github.io/mwhs-data-mobilization/notebooks/socotra_archipelago/Zajonz_et_al_2019/)                                                        | [Link](https://doi.org/10.25607/tzzetb) |
| The Sundarbans                                                                            | Chatterjee 2017                               | Checklist      | [Link](http://support.wwfindia.org/other/State_of_Art_Report.pdf)                                                                                                                                                                                                            | [Link](https://iobis.github.io/mwhs-data-mobilization/notebooks/the_sundarbans/Chatterjee_2017/)                                                               | [Link](https://doi.org/10.25607/b50xdv) |
| The Sundarbans                                                                            | Gupta et al. 2016                             | Checklist      | [Link](https://doi.org/10.11609/jott.1888.8.9.9144-9154)                                                                                                                                                                                                                     | [Link](https://iobis.github.io/mwhs-data-mobilization/notebooks/the_sundarbans/Gupta_et_al_2016/)                                                              | [Link](https://doi.org/10.25607/xxwkfw) |
| The Sundarbans                                                                            | Habib et al. 2020                             | Checklist      | [Link](https://doi.org/10.11609/jott.4893.12.1.15154-15172)                                                                                                                                                                                                                  | [Link](https://iobis.github.io/mwhs-data-mobilization/notebooks/the_sundarbans/Habib_et_al_2020/)                                                              | [Link](https://doi.org/10.25607/mqut2a) |
| The Sundarbans                                                                            | Mishra and Gopi 2017                          | Checklist      | [Link](https://www.researchgate.net/profile/Subhrendu-Mishra/publication/318814335_Fish_diversity_of_Indian_Sundarban_and_its_resource_and_research_prospects/links/59a82702aca272d1b84afc12/Fish-diversity-of-Indian-Sundarban-and-its-resource-and-research-prospects.pdf) | [Link](https://iobis.github.io/mwhs-data-mobilization/notebooks/the_sundarbans/Mishra_2017/)                                                                   | [Link](https://doi.org/10.25607/ufguzy) |
| ~~The Sundarbans~~                                                                        | ~~Habib et al. 2021~~                         | ~~Checklist~~  | [~~Link~~](https://doi.org/10.1371/journal.pone.0255110)                                                                                                                                                                                                                     | \---                                                                                                                                                           | \---                                    |
| The Wadden Sea                                                                            | Jager et al. 2009                             | Checklist      | [Link](https://www.waddensea-worldheritage.org/sites/default/files/2009_Ecosystem25_QSR%202009.pdf)                                                                                                                                                                          | [Link](https://iobis.github.io/mwhs-data-mobilization/notebooks/the_wadden_sea/Jagar_et_al_2009/)                                                              | [Link](https://doi.org/10.25607/egi2u4) |
| The Wadden Sea                                                                            | Wadden Sea Site Species List 2023             | Checklist      | NA                                                                                                                                                                                                                                                                           | [Link](https://iobis.github.io/mwhs-data-mobilization/notebooks/the_wadden_sea/Wadden_Sea_Site_Fish_List_2023)                                                 | [Link](https://doi.org/10.25607/rsyqaa) |
| ~~The Wadden Sea~~                                                                        | ~~Wätjen and Ramírez-Monsalve 2020~~          | ~~Checklist~~  | [~~Link~~](http://dx.doi.org/10.1007/978-3-030-26784-1_7)                                                                                                                                                                                                                    | \---                                                                                                                                                           | \---                                    |
| Tubbataha Reefs Natural Park                                                              | Murray et al. 2019                            | Checklist      | [Link](https://doi.org/10.1016/j.japb.2018.09.009)                                                                                                                                                                                                                           | [Link](https://iobis.github.io/mwhs-data-mobilization/notebooks/tubbataha_reefs_natural_park/Murray_et_al_2019)                                                | [Link](https://doi.org/10.25607/w4dalx) |
| Tubbataha Reefs Natural Park                                                              | White et al. 2019                             | Occurrence     | [Link](https://www.coast.ph/publications/summary-field-report-saving-philippine-reefs-coral-reef-monitoring-expedition-to-tubbataha-reefs-national-marine-park-sulu-sea-philippines-april-21-27-2018/)                                                                       | [Link](https://iobis.github.io/mwhs-data-mobilization/notebooks/tubbataha_reefs_natural_park/White_et_al_2019)                                                 | [Link](https://doi.org/10.25607/jaqexe) |
| Tubbataha Reefs Natural Park                                                              | Tubbataha Management Office Species List 2022 | Checklist      | NA                                                                                                                                                                                                                                                                           | [Link](https://iobis.github.io/mwhs-data-mobilization/notebooks/tubbataha_reefs_natural_park/Tubbataha_Management_Office_2022)                                 | [LInk](https://doi.org/10.25607/oxulyd) |






Built using [TabletoMarkdown](https://tabletomarkdown.com/)
